language: rust
rust:
  - stable
  - beta
  - nightly

install:
  - rustup target add thumbv7em-none-eabihf
  
script:
- cargo build
- cargo test

# Check for no_std compatibility by building for an embedded target
- cargo build --no-default-features --target=thumbv7em-none-eabihf
- cargo build --no-default-features --features=alloc --target=thumbv7em-none-eabihf
